# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a69d21f46adcb4762d5f119ae511e2377c74cfd08fa2e93bf46ab986ad4d3de6cd7cd694ba9a9e5140c19d17a9c7fc815a7fbe780b3221fd6426608d76e673b

test:
  secret_key_base: 0d8575dfef7b0767104e0823171a4f28ee614026e6302d1fb083453346c2243af66fb521b5042f31e4837d0758170b6bbc33d70ced1b2a521da7f011cbb2e009

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
